[[language]]
name = "json"
auto-format = false

[[language]]
name = "toml"

[[language]]
name = "bash"

[[language]]
name = "php"

[[language]]
name = "html"

[[languages]]
name = "bash"
file-types = ["sh", "bash", ".functions"]
